export const invoices = [
  {
    key: "1",
    no: "#24721",
    name: "Admin Asadujjaman",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "2",
    no: "#26552",
    name: "Admin Asadujjaman",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "3",
    no: "#24563",
    name: "Admin Asadujjaman",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "4",
    no: "#2424",
    name: "Dr. Anna KOWALSKA",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "5",
    no: "#247865",
    name: "Dr. Michael O'CONNOR",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "6",
    no: "#24456",
    name: "Dr. Yasmin AL-FARSI",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "7",
    no: "#24727",
    name: "Dr. Leila BEN AMAR",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "8",
    no: "#24578",
    name: "Dr. Elena PETROVA",
    plan: "Monthly",
    duration: "Year",
    price: "23",
    commision: "5",
  },
  {
    key: "9",
    no: "#2499",
    name: "Dr. Sergei IVANOV",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "10",
    no: "#242310",
    name: "Dr. Sofia OLIVEIRA",
    plan: "Monthly",
    duration: "Month",
    price: "23",
    commision: "5",
  },
  {
    key: "11",
    no: "#249811",
    name: "Dr. Ahmed KHAN",
    plan: "Monthly",
    duration: "Year",
    price: "23",
    commision: "5",
  },
];
